### ISSUE TITLE
Tom-select with big label

### ISSUE THREAD

**Issue by benji07** [Elao/elao-admin#56]
On my project options of a tomselect are display with a weird indentation.

![Capture d’écran 2022-08-31 à 14 03 54](https://user-images.githubusercontent.com/166890/187674227-b7cf0f4f-095e-471a-a966-8699dcf927c6.png)

A bit of css is responsible for the bug (display flex)

I made a quick fix in my project by using the following style

```css
.ts-dropdown-content .option {
  display: block;
  min-height: unset;
}
```
